name: Deploy Lambda and Other Assets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOPER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOPER }}
          aws-region: us-east-1

      - name: Upload app-lambda-cam.zip to S3
        run: aws s3 cp ./app-lambda-cam.zip s3://likwi-lambdas-dev/app-lambda-cam.zip

      - name: Upload another-file.zip to S3
        run: aws s3 cp ./another-file.zip s3://likwi-lambdas-dev/another-file.zip

      - name: Upload app-lambda-hom.zip to S3 (Homolog)
        run: aws s3 cp ./app-lambda-hom.zip s3://likwi-lambdas-hom/app-lambda-hom.zip

      - name: Upload assets.zip to S3 (Production)
        run: aws s3 cp ./assets.zip s3://likwi-lambdas-prod/assets.zip

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name my-lambda-function \
            --s3-bucket likwi-lambdas-dev \
            --s3-key app-lambda-cam.zip
