name: Pipeline

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'
  delete:
    branches:
      - 'feature/**'

env:
  STACK_NAME: APP-LAMBDA-CAM-STACK
  DEVELOPER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOPER }}
  DEVELOPER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOPER }}
  DEVELOPER_REGION: us-east-1
  DEVELOPER_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::012821307542:role/CloudFormationExecutionRole
  DEVELOPER_ENVIRONMENT_FILE: infra/environment/developer.json

  PRODUCTION_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
  PRODUCTION_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
  PRODUCTION_REGION: us-east-1
  PRODUCTION_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::012821307542:role/CloudFormationExecutionRole
  PRODUCTION_ENVIRONMENT_FILE: infra/environment/production.json

jobs:
  build-and-deploy-developer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build the Go executable
        run: |
          GOOS=linux GOARCH=amd64 go build -o bootstrap main.go

      - name: Package Lambda function
        run: |
          zip bootstrap.zip bootstrap

      - name: Upload to S3 (Developer)
        run: |
          aws s3 cp bootstrap.zip s3://likwi-lambdas-dev/bootstrap.zip --region ${{ env.DEVELOPER_REGION }}

      - name: Deploy to Developer Stack
        run: |
          aws cloudformation deploy \
            --template-file infra/cf-lambda.yaml \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ env.DEVELOPER_REGION }} \
            --parameter-overrides file://infra/environment/developer.json

  build-and-deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build the Go executable
        run: |
          GOOS=linux GOARCH=amd64 go build -o bootstrap main.go

      - name: Package Lambda function
        run: |
          zip bootstrap.zip bootstrap

      - name: Upload to S3 (Production)
        run: |
          aws s3 cp bootstrap.zip s3://likwi-lambdas-prd/bootstrap.zip --region ${{ env.PRODUCTION_REGION }}

      - name: Deploy to Production Stack
        run: |
          aws cloudformation deploy \
            --template-file infra/cf-lambda.yaml \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ env.PRODUCTION_REGION }} \
            --parameter-overrides file://infra/environment/production.json
